#ThisLike Config

#   Debug ( max / full / Default:normal / none )
Debug: normal

#   MySQL Settings
mysql:
  host: localhost
  port: 3306
  database: ThisLike
  username: root
  password: password

#   Server Version 1.2 or 1.4
Version: 1.4
