#ThisLike Config

#   Debug ( max / full / Default:normal / stop )
Debug: normal

#   MySQL Settings
mysql:
  host: localhost
  port: 3306
  database: ThisLike
  username: root
  password: password

#   Dynmap へ MarkerIcon 表示するか？
OnDynmap: false

#   基本的なメッセージの文字列
like: "いいね"
unlike: "解除"

#   いいね看板と判断するキー文字
SignSetKey: "ThisLike"

#   アドミンネーム
Admin: Server

#   有効な置換文字列
#   &$n = カラーコード
#   %player% = プレイヤー名
#   %title% = 看板タイトル
#   %num% = いいね数

#   設置看板のフォーマット定義
SignBase:
    - "[%$b これイイネ!! %$0]"
    - "%$0%title%"
    - "%$0看板主:%$a%owner%"
    - "%$cイイネ : %$1%num%"

#   いいねをBroadcastで報告する
LikeBroadcast: true

#   いいねした時のプレイヤーメッセージ
#   有効な置換文字列有効
SetLike: "%owner% %$aさんの%$e『%title%』%$aに%$bイイネ%$aしました"

#   いいねした時、オーナーがオンラインならば通知する時のメッセージ
#   有効な置換文字列有効
#   "none" で非通知
InfoLike: "%liker% %$aさんが%$e『%title%』%$aに%$bイイネ%$aしました"

#   解除をBroadcastで報告する
#   ネガティブ要素なのでディフォルトは false
UnlikeBroadcast: false

#   いいね解除した時のプレイヤーメッセージ
#   有効な置換文字列有効
SetUnlike: "%owner% %$dさんの%$e『%title%』%$dから%$bイイネ%$dをやめました"

#   いいねした時、オーナーがオンラインならば通知する時のメッセージ
#   有効な置換文字列有効
#   "none" で非通知
InfoUnlike: "%liker% %$dさんが%$e『%title%』%$dから%$bイイネ%$dをやめました"

#   削除可能時のプレイヤーメッセージ
#   有効な置換文字列有効
Remove: "%$dイイネ看板を無効にしました。%$a破壊可能です"

#   いいね一覧する時のインベントリータイトル
#   有効な置換文字列有効
InventoryTitle: "『%title%』のいいね"

#   自分の看板だった時のメッセージ
#   有効な置換文字列有効
YourSign: "%$aあなたのイイネ看板です"

#   看板登録を削除した時のメッセージ
RemoveSignLore:
    - "§4いいね看板を"
    - "§4削除します"

#   プレイヤーヘッドを本人のものとして読み込む
#   最初の処理で人数が多い場合、全表示まで初回は大きく時間がかかる
MakeHead: false

#   イイネ数による報償制度
Reward:
    enable: false
    sound:
        enabled: true
        type: ENTITY_PLAYER_LEVELUP
        volume: 1
        pitch: 1
    #   イイネ数の倍率、１イイネに対して何倍するか
    magnification: 1
    #   Rewardsのサイクル（日数)
    datecount: 1
    #   実行時のコマンド（複数可）
    #   %count% イイネ総数
    #   %total% イイネ総数 * magnification
    commands:
        - eco give %owner% %total%
        - eco give %owner% %count%
        - giveitem expcube %owner%
        - giveitem kumaorb %owner%
