main: com.mycompany.thislike.ThisLike
name: ThisLike
version: 0.9.4
description: This Like Event Control plugin
author: Kumaisu
database: true
api-version: 1.14
commands:
    ThisLike:
        description: ThisLike Control Command
        permission: ThisLike.admin
        permission-message: You do not have permission.
        usage: /<command> help
        default: op
permissions:
    ThisLike.admin:
        description: Command Permission
        default: op
