main: com.mycompany.thislike.ThisLike
name: ThisLike
version: ${project.version}
description: ${project.description}
author: Kumaisu
database: true
commands:
    ThisLike:
        description: ThisLike Control Command
        permission: ThisLike.admin
        permission-message: You do not have permission.
        usage: /<command> help
        default: op
permissions:
    ThisLike.admin:
        description: Command Permission
        default: op
