name: ThisLike
version: 0.2.2
main: com.mycompany.thislike.ThisLike
description: This Like Event Control plugin
author: Kumaisu
database: true
commands:
    ThisLike:
        description: ThisLike Control Command
        permissions: ThisLike.admin
        permission-message: You do not have permission.
        usage: /<command> help
        default: op
