name: ThisLike
version: 0.3.2
main: com.mycompany.thislike.ThisLike
description: This Like Event Control plugin
author: Kumaisu
database: true
api-version: 1.14
commands:
    ThisLike:
        description: ThisLike Control Command
        usage: /<command> help
permissions:
    ThisLike.admin:
        description: Command Permission
        default: op
